version: "3"

services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sg
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '54320:5432'

  php-apache:
    container_name: php-apache
    build:
      context: .
    ports:
        - '8003:8003'
    volumes:
      - .:/var/www/super_gestao
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
